"""empty message

Revision ID: 698c8736672c
Revises: d9c9977a9ec0
Create Date: 2024-10-01 18:10:07.404435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "698c8736672c"
down_revision: Union[str, None] = "d9c9977a9ec0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_spent_earned",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("total_lost", sa.BigInteger(), nullable=False),
        sa.Column("total_earned", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("casino_spent_earned")
    # ### end Alembic commands ###
