"""Rename total_lost to total_spent

Revision ID: cb4461db5857
Revises: 12e87559c7fd
Create Date: 2024-10-01 19:18:37.483209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4461db5857'
down_revision: Union[str, None] = '12e87559c7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'casino_spent_earned', 
        'total_lost', 
        new_column_name='total_spent',
        existing_type=sa.BigInteger()  # Specify the existing type
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'casino_spent_earned', 
        'total_spent', 
        new_column_name='total_lost',
        existing_type=sa.BigInteger()  # Specify the existing type
    )
    # ### end Alembic commands ###
