"""initial migration

Revision ID: d9c9977a9ec0
Revises: 
Create Date: 2024-09-29 03:14:23.829741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c9977a9ec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('user_gold',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gold', sa.BigInteger(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_inventory',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_inventory')
    op.drop_table('user_gold')
    op.drop_table('submissions')
    # ### end Alembic commands ###
