"""change ids to uuids

Revision ID: f1f582d529fa
Revises: cb4461db5857
Create Date: 2024-10-25 22:50:59.978580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import uuid

# revision identifiers, used by Alembic.
revision: str = 'f1f582d529fa'
down_revision: Union[str, None] = 'cb4461db5857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint before altering columns
    op.drop_constraint('fk_study_plan_problems_study_plan_id', 'study_plan_problems', type_='foreignkey')

    # Change 'id' in study_plans to VARCHAR(36)
    op.alter_column('study_plans', 'id', 
                    type_=sa.VARCHAR(36), nullable=False)

    # Change 'id' in study_plan_problems to VARCHAR(36)
    op.alter_column('study_plan_problems', 'id', 
                    type_=sa.VARCHAR(36), nullable=False)

    # Change 'study_plan_id' in study_plan_problems to VARCHAR(36)
    op.alter_column('study_plan_problems', 'study_plan_id', 
                    type_=sa.VARCHAR(36), nullable=False)

    # Recreate the foreign key constraint after altering the column types
    op.create_foreign_key(
        'fk_study_plan_problems_study_plan_id', 
        'study_plan_problems', 
        'study_plans', 
        ['study_plan_id'], 
        ['id']
    )

    op.drop_column('problems', 'solution_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     # Drop the foreign key constraint before reverting columns
    op.drop_constraint('fk_study_plan_problems_study_plan_id', 'study_plan_problems', type_='foreignkey')

    # Revert 'id' in study_plans to BigInteger
    op.alter_column('study_plans', 'id', 
                    type_=sa.BigInteger(), 
                    nullable=False)

    # Revert 'id' in study_plan_problems to BigInteger
    op.alter_column('study_plan_problems', 'id', 
                    type_=sa.BigInteger(), 
                    nullable=False)

    # Revert 'study_plan_id' in study_plan_problems to BigInteger
    op.alter_column('study_plan_problems', 'study_plan_id', 
                    type_=sa.BigInteger(), 
                    nullable=False)

    # Recreate the foreign key constraint after reverting the column types
    op.create_foreign_key(
        'fk_study_plan_problems_study_plan_id', 
        'study_plan_problems', 
        'study_plans', 
        ['study_plan_id'], 
        ['id']
    )

    
    op.add_column('problems', sa.Column('solution_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###
