name: Deploy to Bloom Host

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Add SFTP server to known_hosts
        shell: bash
        env:
          HOSTNAME: ${{ secrets.BLOOM_HOST_SFTP_HOSTNAME }}
          PORT: ${{ secrets.BLOOM_HOST_SFTP_PORT }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" -H "$HOSTNAME" >> ~/.ssh/known_hosts

      - name: Deploy to SFTP server
        env:
          SFTP_HOSTNAME: ${{ secrets.BLOOM_HOST_SFTP_HOSTNAME }}
          SFTP_PORT: ${{ secrets.BLOOM_HOST_SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.BLOOM_HOST_SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.BLOOM_HOST_SFTP_PASSWORD }}
        run: |
          lftp -u "$SFTP_USERNAME","$SFTP_PASSWORD" "sftp://$SFTP_HOSTNAME:$SFTP_PORT" <<EOF
          set sftp:auto-confirm yes
          mirror -R -e --exclude '^\.env$' --exclude .github --exclude .git --exclude .local --exclude .cache --exclude __pycache__ . .
          bye
          EOF

      - name: Send restart signal
        env:
          BLOOM_HOST_API_KEY: ${{ secrets.BLOOM_HOST_API_KEY }}
          BLOOM_HOST_SERVER_ID: ${{ secrets.BLOOM_HOST_SERVER_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $BLOOM_HOST_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"signal": "restart"}' \
          https://mc.bloom.host/api/client/servers/$BLOOM_HOST_SERVER_ID/power
